package VIEW;

import CONTROL.ControlTelaCadastro;

public class JFrameTelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaCadastro
     */
    public JFrameTelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelCabecalho = new javax.swing.JPanel();
        JohnsBarbeariaJLabel = new javax.swing.JLabel();
        SairJButton = new javax.swing.JButton();
        sejabemvindoJLabel = new javax.swing.JLabel();
        NomeJText = new javax.swing.JTextField();
        NomeJLabel = new javax.swing.JLabel();
        EmailJText = new javax.swing.JTextField();
        EmailJLabel = new javax.swing.JLabel();
        EmailConfimacaoJText = new javax.swing.JTextField();
        EmailConfimacaoJLabel = new javax.swing.JLabel();
        SenhaJText = new javax.swing.JPasswordField();
        SenhaJLabel = new javax.swing.JLabel();
        SenhaConfirmacaoJPassword = new javax.swing.JPasswordField();
        SenhaConfirmacaoJLabel = new javax.swing.JLabel();
        CadastrarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));

        JPanelCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        JPanelCabecalho.setPreferredSize(new java.awt.Dimension(820, 60));

        JohnsBarbeariaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/JOHN’S BARBEARIA cinza.png"))); // NOI18N

        SairJButton.setForeground(new java.awt.Color(65, 65, 65));
        SairJButton.setText("SAIR ✖");
        SairJButton.setBorder(null);
        SairJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SairJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelCabecalhoLayout = new javax.swing.GroupLayout(JPanelCabecalho);
        JPanelCabecalho.setLayout(JPanelCabecalhoLayout);
        JPanelCabecalhoLayout.setHorizontalGroup(
            JPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JohnsBarbeariaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SairJButton)
                .addGap(42, 42, 42))
        );
        JPanelCabecalhoLayout.setVerticalGroup(
            JPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JohnsBarbeariaJLabel)
                .addGap(16, 16, 16))
            .addGroup(JPanelCabecalhoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SairJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sejabemvindoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sejabemvindoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        sejabemvindoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sejabemvindoJLabel.setText("CADASTRO");
        sejabemvindoJLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sejabemvindoJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NomeJText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NomeJText.setForeground(new java.awt.Color(65, 65, 65));
        NomeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeJTextActionPerformed(evt);
            }
        });

        NomeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NomeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomeJLabel.setText("Nome");

        EmailJText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailJText.setForeground(new java.awt.Color(65, 65, 65));

        EmailJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailJLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailJLabel.setText("Email");

        EmailConfimacaoJText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailConfimacaoJText.setForeground(new java.awt.Color(65, 65, 65));
        EmailConfimacaoJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailConfimacaoJTextActionPerformed(evt);
            }
        });

        EmailConfimacaoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailConfimacaoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailConfimacaoJLabel.setText("Confirme seu email");

        SenhaJText.setForeground(new java.awt.Color(65, 65, 65));

        SenhaJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SenhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        SenhaJLabel.setText("Senha");

        SenhaConfirmacaoJPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SenhaConfirmacaoJPassword.setForeground(new java.awt.Color(65, 65, 65));

        SenhaConfirmacaoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SenhaConfirmacaoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        SenhaConfirmacaoJLabel.setText("Corfime sua senha");

        CadastrarJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadastrarJButton.setForeground(new java.awt.Color(65, 65, 65));
        CadastrarJButton.setText("CADASTRAR");
        CadastrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SenhaConfirmacaoJLabel)
                    .addComponent(SenhaJLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EmailConfimacaoJLabel)
                        .addComponent(EmailJLabel)
                        .addComponent(NomeJLabel)
                        .addComponent(NomeJText)
                        .addComponent(EmailJText)
                        .addComponent(EmailConfimacaoJText)
                        .addComponent(SenhaJText)
                        .addComponent(SenhaConfirmacaoJPassword)))
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sejabemvindoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(CadastrarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(354, 354, 354))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JPanelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(sejabemvindoJLabel)
                .addGap(58, 58, 58)
                .addComponent(NomeJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailJLabel)
                .addGap(5, 5, 5)
                .addComponent(EmailJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(EmailConfimacaoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailConfimacaoJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SenhaJLabel)
                .addGap(3, 3, 3)
                .addComponent(SenhaJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(SenhaConfirmacaoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaConfirmacaoJPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(CadastrarJButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairJButtonActionPerformed
        ControlTelaCadastro.SairJButtonActionPerformed();
        this.dispose();
    }//GEN-LAST:event_SairJButtonActionPerformed

    private void NomeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeJTextActionPerformed

    private void EmailConfimacaoJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailConfimacaoJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailConfimacaoJTextActionPerformed

    private void CadastrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarJButtonActionPerformed
        ControlTelaCadastro.CadastrarJButtonActionPerformed(nome_usuario(), email_usuario(), senha_usuario());
        this.dispose();
    }//GEN-LAST:event_CadastrarJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarJButton;
    private javax.swing.JLabel EmailConfimacaoJLabel;
    private javax.swing.JTextField EmailConfimacaoJText;
    private javax.swing.JLabel EmailJLabel;
    private javax.swing.JTextField EmailJText;
    private javax.swing.JPanel JPanelCabecalho;
    private javax.swing.JLabel JohnsBarbeariaJLabel;
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JTextField NomeJText;
    private javax.swing.JButton SairJButton;
    private javax.swing.JLabel SenhaConfirmacaoJLabel;
    private javax.swing.JPasswordField SenhaConfirmacaoJPassword;
    private javax.swing.JLabel SenhaJLabel;
    private javax.swing.JPasswordField SenhaJText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sejabemvindoJLabel;
    // End of variables declaration//GEN-END:variables

    public String nome_usuario() {
        String nome_email = NomeJText.getText();
        return nome_email;
    }

    public String email_usuario() {
        String nome_senha = EmailJText.getText();
        return nome_senha;
    }

    public String senha_usuario() {
        String nome_email = SenhaJText.getText();
        return nome_email;
    }

    public void limpaCampos() {
        NomeJText.setText("");
        EmailJText.setText("");
        SenhaJText.setText("");
    }
}
